version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  api_gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway
    ports:
      - "5000:5000"
    depends_on:
      - user_service_v1
      - user_service_v2
      - order_service
      - rabbitmq

  user_service_v1:
    build:
      context: ./user_service_v1
    container_name: user_service_v1
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
      - mongodb

  user_service_v2:
    build:
      context: ./user_service_v2
    container_name: user_service_v2
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
      - mongodb

  order_service:
    build:
      context: ./order_service
    container_name: order_service
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
      - mongodb
